apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type elasticsearch
      host 
      port 9200
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      type_name _doc
      flush_interval 5s
    </match>
