apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{ .Values.namespace }}
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern ^bookshop$
      </regexp>
    </filter>

    <match **>
      @type elasticsearch
      host {{ .Values.elasticsearch.host }}
      port {{ .Values.elasticsearch.port }}
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      type_name _doc
      flush_interval 5s
    </match>