namespace: logging
image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.16.3-debian-elasticsearch7-1.0
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 200Mi
    cpu: 100m
  requests:
    memory: 100Mi
    cpu: 100m
elasticsearch:
  host: 34.134.183.210
  port: 9200