replicaCount: 1

apiGateway:
  image: nahidacunny/bookshop-api_gateway:v1.0.3-22052025-06-32-12
  port: 8000

authService:
  image: nahidacunny/bookshop-auth_service:v1.0.8-21052025-11-58-22
  port: 8001
  jwtSecretKey: ""
  smtp:
    server: ""
    port: ""
    senderEmail: ""
    senderPassword: ""

bookService:
  image: nahidacunny/bookshop-book_service:v1.0.5-18052025-13-09-53
  port: 8002

cartService:
  image: nahidacunny/bookshop-cart_service:v1.0.3-22052025-10-32-16
  port: 8003

frontend:
  image: nahidacunny/bookshop-frontend:v1.0.15-22052025-13-06-10
  port: 80

mongodb:
  image: mongo:latest
  port: 27017
  storage: 5Gi
