replicaCount: 1

apiGateway:
  image: nahidacunny/bookshop-api_gateway:v1.0.2-08052025-13-26-49
  port: 8000

authService:
  image: nahidacunny/bookshop-auth_service:v1.0.3-08052025-13-02-44
  port: 8001
  jwtSecretKey: ""
  smtp:
    server: ""
    port: ""
    senderEmail: ""
    senderPassword: ""

bookService:
  image: nahidacunny/bookshop-book_service:v1.0.2-08052025-13-26-49
  port: 8002

cartService:
  image: nahidacunny/bookshop-cart_service:v1.0.2-08052025-13-26-49
  port: 8003

frontend:
  image: nahidacunny/bookshop-frontend:v1.0.1-08052025-14-03-29
  port: 80

mongodb:
  image: mongo:latest
  port: 27017
  storage: 5Gi
