apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: ClusterIP
  selector:
    app: book-service
  ports:
    - port: {{ .Values.bookService.port }}
      targetPort: {{ .Values.bookService.port }}
